// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snippet03.Models
{
    public partial class Price
    {
        public int Id { get; set; }
        public int TickerId { get; set; }
        public decimal Price1 { get; set; }
        public DateTime? Date { get; set; }

        public virtual Ticker Ticker { get; set; }
    }
}