// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snippet03.Models
{
    public partial class Ticker
    {
        public Ticker()
        {
            Prices = new HashSet<Price>();
            TodaysConditions = new HashSet<TodaysCondition>();
        }

        public int Id { get; set; }
        public string Ticker1 { get; set; }

        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<TodaysCondition> TodaysConditions { get; set; }
    }
}