// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snippet03.Models
{
    public partial class TodaysCondition
    {
        public int Id { get; set; }
        public int TickerId { get; set; }
        public byte State { get; set; }

        public virtual Ticker Ticker { get; set; }
    }
}